version = 0.1

[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "jipag"
github_repo = "sam-app"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::766950428962:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-ixQFkO1bRGhp"
cloudformation_execution_role = "arn:aws:iam::766950428962:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-lDJeZOplbYv8"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-8slv19bvenlu"
image_repository = ""
region = "us-west-2"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::766950428962:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-vsp34XlGWqhz"
cloudformation_execution_role = "arn:aws:iam::766950428962:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-p7V4tqpaixDL"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-iesyp4gd1yav"
image_repository = ""
region = "us-west-2"
